import "dotenv/config";
import { getWorkspace, closePool, one, query } from "../src/lib/db";
import { projectGraph } from "../src/lib/graph/project";
import { resolveRun } from "../src/lib/resolution/resolve";

/**
 * Rebuilds L2 through L4 from the claim ledger.
 *
 * This is the command that proves the architecture: if it can be run at any time
 * and produce the same graph, then extraction output is the only thing that
 * matters and every derived table is disposable. Run it after changing
 * resolution weights, edge scoring, or the dossier format.
 */
async function main() {
  const ws = await getWorkspace();
  const keepEntities = process.argv.includes("--keep-entities");

  // Entity ids are regenerated by a rebuild, so the workspace's self pointer has
  // to be re-bound by name afterwards — otherwise every path loses its origin.
  const previousSelf = ws.self_entity_id
    ? await one<{ canonical_name: string }>(`SELECT canonical_name FROM entities WHERE id = $1`, [
        ws.self_entity_id,
      ])
    : null;

  if (!keepEntities) {
    console.log("Clearing derived tables (entities, edges, links, metrics)…");
    await query(
      `TRUNCATE search_queries, edge_evidence, entity_metrics, edges, resolution_reviews,
                entity_merges, mention_links, entity_aliases, entities RESTART IDENTITY CASCADE`,
    );

    const runs = await query<{ id: string; title: string }>(
      `SELECT r.id, s.title FROM extraction_runs r
       JOIN sources s ON s.id = r.source_id
       WHERE s.workspace_id = $1 AND r.status = 'succeeded'
       ORDER BY COALESCE(s.occurred_at, s.ingested_at) ASC`,
      [ws.id],
    );

    // Chronological order matters: resolution uses the graph built so far as
    // evidence, so replaying in the original sequence reproduces the decisions.
    for (const run of runs) {
      const summary = await resolveRun(ws.id, run.id);
      console.log(
        `  ${run.title}: +${summary.created} new, ${summary.matched} matched, ` +
          `${summary.queued} queued, ${summary.deferred} deferred`,
      );
    }
  }

  const result = await projectGraph(ws.id);
  console.log(`Projected ${result.entities} entities and ${result.edges} edges.`);

  if (previousSelf) {
    const self = await one<{ id: string }>(
      `SELECT id FROM entities WHERE workspace_id = $1 AND entity_type = 'person'
         AND lower(canonical_name) = lower($2) AND status <> 'merged' LIMIT 1`,
      [ws.id, previousSelf.canonical_name],
    );
    if (self) {
      await query(`UPDATE workspaces SET self_entity_id = $2 WHERE id = $1`, [ws.id, self.id]);
      console.log(`Re-bound self node to "${previousSelf.canonical_name}".`);
    } else {
      console.warn(
        `Could not re-bind the self node ("${previousSelf.canonical_name}") — set workspaces.self_entity_id manually.`,
      );
    }
  }
  await closePool();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
